### ISSUE TITLE
Public release of additional truth information for DC2

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/desc-data-portal#88] opened 2022-01-18 21:57 UTC
Access to DC2 truth info such as SN parameters, stellar types, variability light curves, cluster locations, etc., has been requested by DP0 delegates, and the Rubin project has inquired if those data could be made available.  This can be done by publicly releasing the data ourselves: making them available through the Data Portal and revising the Release Note.  Initial discussion took place on [slack](https://lsstc.slack.com/archives/C01E1FG9Y4B/p1642438015000700).   We can use this issue to track the work.

HK: Adding a checklist to make sure we don't forget anything
### To Do List

- [x] Create and Assemble the files - Joanne
- [x] Update GCRCatalogs - Joanne & Yao
- [x] Copy data into the appropriate area for the data portal - Heather
- [x] Update Portal documentation - Yao
- [x] Create tutorial notebook - Yao
- [x] Update DC2 Data Release Note - Yao
- [x] Copy data to ANL shared endpoint - Katrin
- [x] Update portal yaml  - Heather
- [x] Deploy new portal to dev server - Heather
- [x] Release new version to the production server - Heather
- [x] Announce on #desc-announce and Community - Joanne (?)

**Comment by heather999** [comment] 2022-01-26 03:47
Can we list what data we want to include and then start noting where this data resides?  From the Slack message I see:
* truth light curves
* SN parameters
* star variability types
* cluster locations

**Comment by jchiang87** [comment] 2022-01-26 05:16
Here are the locations of the input catalogs used to generate instance catalog entries for the various non-galaxy components:
* stars: ` /global/cfs/cdirs/descssim/DC2/dc2_stellar_healpixel.db`
* Run2.1i SNe: `/global/cfs/cdirs/descssim/DC2/sne_params_wfd_cosmodc2_180911.db`
* Run3.1i AGNs: `/global/cfs/cdirs/descssim/DC2/Run3.0i/truth_tables/updated_lensed_agn_truth.db`

**Comment by JoanneBogart** [comment] 2022-01-28 01:41
I've created files `star_truth_summary_trimmed.db` , `star_truth_summary_trimmed.parquet`. They can be found alongside the originals under `/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/truth/startruth`.  They have the same stars as the `star_lc_stats_trimmed` files.

**Comment by JoanneBogart** [comment] 2022-01-28 18:58
About Run2.2i SNe:  the config file says `/global/projecta/projectdirs/lsst/groups/SSim/DC2/cosmoDC2_v1.1.4/sne_cosmoDC2_v1.1.4_MS_DDF.db`   
but of course there is no projecta any more.  More or less following sym links leads to
`/global/cfs/cdirs/descssim/DC2/cosmoDC2_v1.1.4/sne_cosmoDC2_v1.1.4_MS_DDF.db` which seems like the best candidate.  It's slightly newer and bigger than the file mentioned above.

**Comment by JoanneBogart** [comment] 2022-01-28 23:21
>  I expect we'd want a "trimmed" version of the star_variability_truth.db data set.

Is this just a rename or does it currently include rows for stars outside the trimmed set?

**Comment by jchiang87** [comment] 2022-01-28 23:30
I don't recall what's in it.  Since it doesn't have `trimmed` in the name, I would have guessed it has all of the stars, but maybe it is trimmed already.

**Comment by JoanneBogart** [comment] 2022-01-29 00:12
Just looking at the first bunch of ids (ordered) in the variability file it appears they're all in the trimmed set but I haven't proved it yet.  The total number of distinct ids in the variability table is less than 739000, as compared to nearly 10 times as many (6883094) rows in the trimmed summary table. Is that to be expected?

**Comment by jchiang87** [comment] 2022-01-29 00:28
> The total number of distinct ids in the variability table is less than 739000, as compared to nearly 10 times as many (6883094) rows in the trimmed summary table. Is that to be expected?

I think so.  In the DC2 paper, it says "Variability is incorporated within the stellar catalogs with approximately 10\% of the stellar sources expected to be variable at a level detectable by LSST"  (section 5.3).  So we omitted stars that would have detectable variability.

**Comment by JoanneBogart** [comment] 2022-01-29 00:44
Good, that's reassuring.  And I've confirmed that none of the trimmed ids appear in the variability table.

**Comment by yymao** [comment] 2022-02-02 19:24
Here's how to get all the low-z (z < 0.5) clusters (mass > 1e14) positions from cosmoDC2. 

The middle step where I obtain the healpixels from truth catalog is not really necessary if one doesn't mind a longer run time. 

Side note: I realized that we only provide the HDF5 version of cosmoDC2, not the parquet version, which makes this simple task rather slow... 

```python
import numpy as np
import GCRCatalogs
GCRCatalogs.set_root_dir("/global/cfs/cdirs/lsst/gsharing")

truth_cat = GCRCatalogs.load_catalog("desc_dc2_run2.2i_dr6_truth")
healpix_needed = set()
for data in truth_cat.get_quantities(
    ["cosmodc2_hp"], 
    filters=["match_objectId > -1", "cosmodc2_hp > -1"], 
    return_iterator=True,
):
    healpix_needed.update(np.unique(data["cosmodc2_hp"]))

cosmodc2 = GCRCatalogs.load_catalog("desc_cosmodc2", config_overwrite={"healpix_pixels": list(healpix_needed)})
cluster_data = cosmodc2.get_quantities(
    ['ra','dec', 'halo_mass', 'halo_id'], 
    filters=['is_central', 'halo_mass > 1e14', 'redshift < 0.5'], 
    native_filters=["redshift_block_lower == 0"],
)
```

**Comment by jchiang87** [comment] 2022-02-07 20:43
@MelissaGraham @jeffcarlin I'd like to draw your attention to Yao's comment above.  The cluster locations in DC2 can be found using the procedure he describes.  Since it uses already-public data, we aren't currently planning to include cluster locations in our update to the DC2 truth info.

**Comment by MelissaGraham** [comment] 2022-02-08 03:57
Thanks @jchiang87 -- one follow-up question (if it's not appropriate for this thread we could Slack about it) where would we access that catalog? At the RSP currently we just have the Truth Match (matched to Object).

**Comment by yymao** [comment] 2022-02-08 04:21
@MelissaGraham CosmoDC2 can be downloaded from the DESC Data Portal as well: https://data.lsstdesc.org/doc/cosmodc2

We also have a parquet version of cosmoDC2 that is on NERSC but not on Data Portal. If the file format makes a difference I think we can share the parquet version as well.

**Comment by JoanneBogart** [comment] 2022-02-08 22:05
@MelissaGraham  from our public data portal https://data.lsstdesc.org/    Look for CosmoDC2.   Our plan is to put the other new truth information on the portal as well.

**Comment by JoanneBogart** [comment] 2022-02-08 22:27
I think this is what's left to be done:
* decide whether we want parquet, SQLite or both for the star and SN tables (I vote for both).  All the files can be found in the NERSC shared area
* consider whether some of them should be renamed for the Portal
* install the files (star and SN tables; SN parameters db) in the Portal
* add some documentation for the new stuff, at a minimum the schemas for the tables

**Comment by JoanneBogart** [comment] 2022-02-28 17:52
A couple last questions for @yymao @heather999 @jchiang87 
* Consistency:  For stars all three SQLite files have ID a string.  For parquet the light curve file has ID an int, for efficiency, but the other two have a string ID.   Should I remake the other two with int ID?  (I'd still leave SQLite files alone)
* GCRCatalogs:  Is there anything to be gained by adding GCRCatalogs entries for the portal parquet files?   It would only be to register them without any readers.

**Comment by heather999** [comment] 2022-02-28 23:55
Certainly there will be other opinions - but I'll offer mine :)

I'd remake the parquet files so that all have ID as an int.  It's better to be consistent and if efficiency is at all in question, it would be easier to handle this now rather than later.

I think registering the parquet files into GCRCatalogs makes sense even without readers.  It would be nice to get into the habit of register our data products - that may not be within GCRCatalogs forever, but we should try to track all of our data files somewhere and GCRCatalogs is the tool we have today.

**Comment by yymao** [comment] 2022-03-01 16:40
I agree with Heather. But I am a bit confused about the GCRCatalogs question. Why won't there be a reader associated with the parquet file? I thought we have plain parquet reader that we can use? 

If there's no reader, how will we release the parquet version to the public?

**Comment by JoanneBogart** [comment] 2022-03-01 17:24
I also think it's better to be consistent with id data type for the parquet files and am in the process of making the new files.
I'll plan on making configs for the new files as well.  If it works right off the bat to use the generic parquet reader I'll put that in - I guess it should.   
Concerning the more general question of how we release files to the public - I don't think we should feel obligated to provide a customized interface to files in a standard format like parquet.

**Comment by yymao** [comment] 2022-03-01 17:33
> Concerning the more general question of how we release files to the public - I don't think we should feel obligated to provide a customized interface to files in a standard format like parquet.

I don't disagree with that point, but we have been providing the GCRCatalogs interface for the parquet files that we have released publicly so far. If there is a very good reason to stop doing that, I may be convinced. Otherwise it seems strange to offer some parquet files with GCRCatalogs and some without?

**Comment by JoanneBogart** [comment] 2022-03-01 17:37
If it's easy (as it probably is for the parquet files) I have no objection. We have nothing similar for the sqlite files and I don't propose we try to create anything.

**Comment by JoanneBogart** [comment] 2022-03-02 23:13
I think this is the final list of files to be copied to the portal
Star tables, all to be found in shared area under `DC2-prod/Run2.2i/truth/startruth`, total size about 100Gbyte
* `star_truth_summary_trimmed_int_id.parquet`
* `star_truth_lc_stats_trimmed_int_id.parquet`
* `star_variability_truth_int_id.parquet`
* `star_truth_summary_trimmed.db`
* `star_lc_stats_trimmed.db`
* `star_variability_truth_indexed.db`
SN tables under `DC2-prod/Run2.2i/truth/sn`, total about 4 Gbytes
* `sn_truth_sumary.parquet`
* `sn_variability_truth.parquet`
* `sum_variable-31mar.db`
SN parameters file, about 64 Mbytes
`/global/cfs/cdirs/descssim/DC2/cosmoDC2_v1.1.4/sne_cosmoDC2_v1.1.4_MS_DDF.db`

**Comment by JoanneBogart** [comment] 2022-03-02 23:32
@heather999 @yymao How should we organize these files in the portal?
Maybe separate folders for star truth and SN truth 
`lsstdesc-public/dc2/run2.2i-dr6-v2/truth_star`    (or `star_truth`) and similar for SN.
Then under each of those one folder for parquet files and another for the SQLite files?

**Comment by yymao** [comment] 2022-03-03 13:40
I think we can put them all under `lsstdesc-public/dc2/run2.2i-dr6-v2/truth_variable` but I don't feel very strongly about this.

**Comment by heather999** [comment] 2022-03-07 18:26
sorry I've been out the last few days.  I'm rather agnostic on this. If we think folks might just want to grab the whole directory, maybe having under one directory makes sense - I guess altogether it could be large for a laptop user at ~360 GB.  
Maybe just let me know that we're settled and we can copy them over to the gsharing area.

**Comment by JoanneBogart** [comment] 2022-03-07 23:08
I think at least the parquet files should be separated from the sqlite files since the sqlite star variability file is rather large.  People serious about working with the star tables will want sqlite; those just wanting to browse may prefer parquet.   Currently I also have star files separate from SN files.  That's not so necessary, but since that's the way it is now it would certainly be simpler for me (if likely more of a bother for you) to leave it as is.  But I can change it if it complicates setting it up on the Portal

**Comment by yymao** [comment] 2022-03-09 16:33
I am working on the tutorial but encounter some questions:
 
1. The `lc_stats` catalog only exists for stars, not SNe? Is that intentional? 
2. Can we copy the data to gsharing? That would make it easier to test the tutorial code with the [new PR in gcr-catalogs](https://github.com/LSSTDESC/gcr-catalogs/pull/587).

**Comment by heather999** [comment] 2022-03-09 17:45
@JoanneBogart I'm anticipating the files will be stored in `/global/cfs/cdirs/lsst/gsharing/lsstdesc-public/dc2/run2.2i-dr6-v2` and we would then see `sntruth` and `startruth` subdirectories under that area.

**Comment by yymao** [comment] 2022-03-09 17:48
I'd still advocate for `truth_variable`. 

If we must split stars and SNe, I think the folder should be called `truth_star` and `truth_sn` (to be more consistent with `truth_match`

**Comment by heather999** [comment] 2022-03-09 17:50
That's fine with me, I just ask that we try to be consistent with what is used under the `shared` area - and we still have time to rename :)

**Comment by JoanneBogart** [comment] 2022-03-09 18:02
So what's the final decision?   I don't think it's necessary to put star and SNe in separate directories; I was more concerned about parquet/sqlite.    So should we just go with everything under truth_variable?

**Comment by yymao** [comment] 2022-03-09 18:15
That'd be my vote!

**Comment by JoanneBogart** [comment] 2022-03-09 18:48
Ok.  I will adjust configs accordingly.

**Comment by JoanneBogart** [comment] 2022-03-09 19:05
Here is a list of the files which need to be copied. 
Relative to `/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/truth/startruth`
`star*int_id.parquet`
`star_truth_summary_trimmed.db`
`star_lc_stats_trimmed.db`
`star_variability_truth_indexed.db`

Relative to `/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/truth/sntruth`
`sn_truth_summary.parquet`
`sn_variability_truth.parquet`
`sum_variable-31mar.db`

And finally, relative to nothing,
`/global/cfs/cdirs/descssim/DC2/cosmoDC2_v1.1.4/sne_cosmoDC2_v1.1.4_MS_DDF.db`

Note this is _almost_ identical to the list posted earlier here.  The difference is that the names of the `int_id` files no longer include `trimmed`

**Comment by JoanneBogart** [comment] 2022-03-09 20:23
The basenames for all files are the same for copies in NERSC shared area and Portal. The hierarchy is flattened for the Portal, but I don't think that's a problem.

**Comment by heather999** [comment] 2022-03-09 20:47
Ok - files copied to: `/global/cfs/cdirs/lsst/gsharing/lsstdesc-public/dc2/run2.2i-dr6-v2/truth_variable`  Let me know if anything seems missing.  I'll start getting this area added to the portal (and have started to look at #84)

**Comment by yymao** [comment] 2022-03-09 21:48
As I am working on the tutorial, I have another question for @JoanneBogart and others: 

The entries in `star_truth_summary_int_id.parquet` and  `star_lc_stats_int_id.parquet`  are identical (i.e., the same set of stars). However, the order of the IDs in these two files are not the same. This mean for any practical purpose one must re-sort or merge these two table. 

Is there a reason for this? Should we provide these two tables. Can we reorder the entries in them (or one) so that their entries are in the same order?

**Comment by yymao** [comment] 2022-03-09 22:39
Follow up the question above -- if the rows in these two files have the same order, we can actually register them as a single "catalog" in GCRCatalogs using the composite feature.

**Comment by yymao** [comment] 2022-03-09 22:59
One more issue that I encountered when developing the tutorial: the `star_variability_truth_int_id.parquet` file is too big to be loaded into memory on NERSC jupyter, and on most laptops I think (the file is 7.6GB, but note that when working with tutorial/notebooks, there's usually other data that are already loaded into memory). 

Does this file need to be a single file? We split other catalogs by sky areas so that each file is 1GB or less, which makes sense. Should we do the same to `star_variability_truth_int_id.parquet`?

**Comment by JoanneBogart** [comment] 2022-03-09 23:20
You can read it in by row groups , of which there are 22.   The parquet truth reader will do this if you use the iterator.

**Comment by JoanneBogart** [comment] 2022-03-09 23:27
It's not sorted spatially; the caller would have to run through the row groups and discard what's not needed.  But there are other ways to sort which would be useful for some (admittedly probably less common) use cases.

**Comment by JoanneBogart** [comment] 2022-03-09 23:32
Concerning the earlier question about the different ordering in `star_truth_summary_int_id.parquet` and `star_lc_stats_int_id.parquet` - there is no particular reason for it; it's an accident of history.   Sorting by (integer) value of id seems like the logical choice, and neither one of them has that ordering now.  I'll see about rewriting them.

**Comment by JoanneBogart** [comment] 2022-03-10 00:57
The sorted files have been created.   The old files are still there but have been renamed to `..._unsorted.parquet`

**Comment by yymao** [comment] 2022-03-10 14:35
Thanks @JoanneBogart @heather999 . 

I'm continuing my work on the tutorials. The previous issues have been resolved (iterating over row groups works; the two summary files now have the same order and I created a composite catalog for them). 

I now encounter a new issue. I selected 3 stars from the summary catalog and want to grab their light curve. They all have non-zero `stdev_r`, so I thought I would find them in the variability table but none of them is.  Is there a cut on some properties in terms of which stars go into the variability table? @jchiang87 @JoanneBogart 

Here's the ID of the stars I selected. 
```python
star_ids = [31107867006, 31303744322, 31411992640]
```

**Comment by JoanneBogart** [comment] 2022-03-10 15:24
@yymao yes I believe there is a cut; likely @jchiang87 knows what it is.  Practically all stars have some variability but we don't store all the light curves.  This came up in some Slack thread not too long ago; maybe I can find it.

**Comment by jchiang87** [comment] 2022-03-10 15:31
Here's the threshold: https://github.com/LSSTDESC/sims_TruthCatalog/blob/master/python/desc/sims_truthcatalog/stellar_variability.py#L344

**Comment by yymao** [comment] 2022-03-10 15:38
Thanks @jchiang87 @JoanneBogart. I'll add this to the tutorial. We should make sure that we mention this threshold in the release note as well.

**Comment by JoanneBogart** [comment] 2022-03-22 00:52
@yymao @jchiang87 I'm posting below the schema I believe we agreed upon: the four tables `truth_star_summary`, `truth_star_variability`, `truth_sn_summary`, `truth_sn_variability`. Please let me know if anything doesn't look right.
```
truth_star_summary
==================
id              id for the star (int)
ra              right ascension
dec             declination
model           variability model
is_variable     flag indicating if variability exceeds threshold (detectable
                by LSST)
flux_u          flux in u-band
flux_g          flux in g-band
flux_r          flux in r-band
flux_i          flux in i-band
flux_z          flux in z-band
flux_y          flux in y-band
Rv              Milky Way extinction parameter at SN location
Av              Milky Way extinction parameter at SN location


truth_star_variability
======================
id              id for the star (int)
obsHistID       visit number
MJD             modified Julian date of observation
bandpass        bandpass of observation
delta_flux      delta from mean flux for this bandpass

truth_sn_summary
================
id              id for the SN
id_int          unique integer id, generated from id and possibly host
                galaxy, algorithm TBD
host_galaxy     id for the host galaxy
ra              right ascension of the SN
dec             declination of the SN
redshift        redshift of the SN
mB              model parameter
t0              model parameter
x0              model parameter
x1              model parameter
max_flux_u      max flux observed in u-band
max_flux_g      max flux observed in g-band
max_flux_r      max flux observed in r-band
max_flux_i      max flux observed in i-band
max_flux_z      max flux observed in z-band
max_flux_y      max flux observed in y-band
Rv              Milky Way extinction parameter at SN location
Av              Milky Way extinction parameter at SN location

truth_sn_variability
====================
id              id for the SN  (string)
id_int         unique integer id, generated from id and possibly host
                galaxy, algorithm TBD
obsHistID       visit number
MJD             modified Julian date of observation
bandpass        bandpass of observation
delta_flux      delta from mean flux for this bandpass

```

**Comment by jeffcarlin** [comment] 2022-03-22 01:15
Are there some columns in the table from which `truth_star_variability` is pulled that give the simulated lightcurve parameters (i.e., period, amplitude, maybe t_0, type of variable -- for periodic variables)? Any parameters that enable reconstructing what was actually simulated will be useful for DP0 delegates looking to test their algorithms. 

Or maybe that is all contained in the "variability model"? (I'm unfamiliar with what is included in the `model` column of the table.)

**Comment by JoanneBogart** [comment] 2022-03-22 01:20
It is not entirely self-contained since the input needed to produce the light curve of the object in question can include a filepath for a template light curve. We're not including those files.

**Comment by JoanneBogart** [comment] 2022-03-22 01:51
I don't think so, or at least not always, but others would know better.  For model type "kplr" the parameters look like this:
{"m":"kplr", "p":{"lc":11074131, "t0":3625.852}}
There are files of light curves organized spatially.  I think the number above associated with the "lc" key is an index into the relevant file.
Somewhat less than half the stars in the table I'm looking at are of type "kplr"

**Comment by JoanneBogart** [comment] 2022-03-22 01:56
The db I'm looking at also has a column "sedFilename" but the values (i.e., filenames) 
don't tell you much.

**Comment by jchiang87** [comment] 2022-03-28 18:50
For the `truth_star_summary` table defined above, the `is_variable` flag is set to `True` if the star's variability exceeds some threshold.  The stars in `/global/cfs/cdirs/lsst/shared/DC2-prod/Run2.2i/truth/startruth/star_variability_truth.db` (on which I assume we will base `truth_star_variability`) were selected if stdev(delta_mag) > 1e-3 in any band, where the delta_mag values are the delta magnitudes of the light curves for those stars, relative to their average magnitudes, computed over the 5-year DC2 span at ~2 day cadence.  This corresponds to 1 mmag of variability.  I note that the nominal photometric accuracy for a single visit is 10 mmag (See https://www.lsst.org/scientists/keynumbers).  Since the actual relative accuracy of an observation depends on how bright the object is, the bandpass, the sky background level, etc., I think that using a lower threshold of 1 mmag makes sense.  However, instead of the `is_variable` flag, I propose that we have a column which is the maximum value over all six bands of stdev(delta_mag), so that users can make their own selections on variability level, and we can say in the documentation that a 1 mmag threshold was used for including stars in `truth_star_variability`.

**Comment by yymao** [comment] 2022-03-29 00:50
Sounds good. It would still be useful to have a flag in the summary to indicate if that entry appear in the variability table.

**Comment by JoanneBogart** [comment] 2022-03-29 16:34
`is_variable` doesn't seem like a great name, especially since previously it meant something else. How about `meets_threshold` ?

**Comment by jchiang87** [comment] 2022-03-29 16:38
I'd suggest `above_threshold` to make the sense really explicit.

**Comment by JoanneBogart** [comment] 2022-03-30 23:06
I've made SQLite files for tables `truth_sn_summary` and `truth_star_summary`; parquet versions are next.  What should the files be called?  I would like to incorporate version information, e.g.
`truth_sn_summary_v1-0-0.db` and `truth_sn_summary_v1-0-0.parquet`
Are there other suggestions?
I'm not fond of using `.` as a separator but will if that's the consensus.

**Comment by heather999** [comment] 2022-04-01 16:50
Is this ready to be copied over to the portal area in `/global/cfs/cdirs/lsst/gsharing/lsstdesc-public`?

**Comment by jeffcarlin** [comment] 2022-04-01 16:54
Hi all - I really like Jim's idea of including a max stdev(delta_mag) to enable simple selection of things with large amplitude variability.

I think it is very important that we find a way to provide lightcurve parameters for the simulated periodic variable stars. This is likely one of the first things that DP0.2 delegates will request (there is a large community eagerly awaiting time-domain data products!), so if we don't provide it initially, we'll get a ton of questions about that as soon as DP0.2 goes live. 

According to the DC2 overview paper, "For sources with well-defined periodic variability (e.g., RR Lyrae and Cepheids) a light curve is generated from an amplitude, period, and a phase." Is there a way to find the amplitude/period/phase for those stars? (My guess is that "kplr" variables are just scaled templates of low-amplitude, non-periodic M-dwarf variability -- are there RR Lyrae/Cepheid types in the "model" category, and would we be able to extract their lightcurve parameters?

**Comment by JoanneBogart** [comment] 2022-04-01 16:56
> Is this ready to be copied over to the portal area in /global/cfs/cdirs/lsst/gsharing/lsstdesc-public?

Not entirely.   Ultimately there will be 8 files: 4 each SQLite and parquet.  I might finish them off today.

**Comment by jchiang87** [comment] 2022-04-01 17:26
@jeffcarlin From the DESC side, I think we'd like to release the tables as currently implemented as soon as possible.  However, I agree that it would be extremely useful for DP0.2 delegates to have the light curve parameters associated with these data.  If we provide the template files and pointers to the relevant lsst_sims code, would the Community Engagement Team be able to devote some resources to extract that information?  DESC doesn't really have the person-power to devote to this right now, but we would certainly be available to consult if CET does the bulk of the work.  DESC could then include that info in a subsequent release so that it is available outside of the Data Previews.

**Comment by jeffcarlin** [comment] 2022-04-01 18:46
Yes, we (CET) can definitely dedicate some effort to that, and would be happy to do so. The templates themselves may not even be necessary if the lightcurve parameters are already in the database(s), but templates would be helpful, too. 

Pointers/tips are welcome, and then I can start digging and will probably have a lot of questions. Thanks!

**Comment by jchiang87** [comment] 2022-04-01 19:32
I just made a [#desc-dc-lightcurves](https://app.slack.com/client/T06D204F2/C039SF1H7NF) channel on Slack.  Let's have the technical discussions there for extracting the light curve truth info from the inputs.  Anyone interested is welcome to join.

**Comment by yymao** [comment] 2022-04-20 17:05
To generate the truth match catalog, one can follow the instructions at https://github.com/LSSTDESC/DC2-production/blob/master/scripts/README_merge_truth_per_tract.md

A side note (that we should add it into the README but we haven't): for the "environment setup" one would need to use desc-stack, not desc-python.

As the instruction points out, we would need to use the `merge_truth_per_tract.py`, but it assumes the schema of the galaxy, star, SN truth catalogs are the same. We will need to update the script to accommodate our new truth catalogs. 

The line that needs to be changed is this one: 
https://github.com/LSSTDESC/DC2-production/blob/a6ff636ea6f779edc7ddf7b91449336e10e14b4a/scripts/merge_truth_per_tract.py#L85 

Based on the [pandas.concat documentation](https://pandas.pydata.org/docs/reference/api/pandas.concat.html), it should work if we just change it to 
```python
df = pd.concat(df_to_merge, join="inner", ignore_index=True)
```
However, this still assumes that the columns that with overlapping names share the same schema. I think currently `id` is string for SN and integer for the rest. So we might want to add a few line before the `concat` line to homogenize the id columns. Also we should check if the `flux_X` columns present in all three catalogs (did we use a different name in SN?) -- if we use different column names, then `join='inner'` won't work out of box and some more edits will be needed.

**Comment by yymao** [comment] 2022-04-20 17:48
I just recalled another column that may not exist in all three types of truth but we still want to keep is `redshift`. Before the merge we can set `redshift` to 0 if it doesn't present in a table.

**Comment by JoanneBogart** [comment] 2022-04-20 19:23
Indeed the flux_X columns don't exist for SNe.  The columns that do exist have a different name (max_delta_flux_X) because they have a different meaning.  I don't think they should be mixed.  I would set flux_X to zero for SNe, as was the case before.

**Comment by yymao** [comment] 2022-04-20 19:45
Right, thanks for the reminder. So I think we need to check some of these unmatched columns (flux, redshift) before the concat line and set them to zero if missing.

**Comment by JoanneBogart** [comment] 2022-05-26 23:07
All the final versions (I believe!) of new files exist in the shared area.  Relative to 
`/global/cfg/cdirs/lsst/shared/DC2-prod/Run2.2i/truth` they are
`truth_galaxy_summary_v1-0-0/`
`truth_merged_summary_v1-0-0/`
`startruth/truth_star_summary_v1-0-0.X`
`startruth/truth_star_variability_v1-0-0.X`
`sntruth/truth_sn_summary_v1-0-0.X`
`sntruth/truth_sn_variability_v1-0-0.X`

where `X` may be either `db` or `parquet`

**Comment by heather999** [comment] 2022-05-31 15:28
I'd like to confirm where the above files should be copied to under gsharing.  There was an older conversation about this here: https://github.com/LSSTDESC/desc-data-portal/issues/88#issuecomment-1058051653
I'm not clear on what we decided.  are we using the `/global/cfs/cdirs/lsst/gsharing/lsstdesc-public/dc2/run2.2i-dr6-v2/truth_variable` area? It looks like it was updated in the last month. Should some of the [above files](https://github.com/LSSTDESC/desc-data-portal/issues/88#issuecomment-1139131498) replace anything that is already in this truth_variable directory? Or are these meant to go into another directory?

**Comment by JoanneBogart** [comment] 2022-05-31 16:32
I didn't envision replacing anything; I assumed the new stuff would be added, one way or another. I have no strong feelings about how we do the versioning except that, as much as possible, naming should be consistent.  I agree with the idea of having v4 in there for all the stuff which is associated with the new release note.

**Comment by JoanneBogart** [comment] 2022-05-31 18:02
Do we need copies?  I was thinking the items under `../run2.2i-dr6-v4` could be the things which are _new_ with this release.   If we need everything belonging to v4 together, is it possible to use sym links for the older stuff.

Concerning subdirectories of `../run2.2i-dr6-v4` the characteristics of the catalogs we can use for organization are
* kind of source (galaxy, star, sn, or merged)
* kind of data (summary or variability)
so in particular galaxy summary does not belong together with truth match (which is merged) and summary files shouldn't be under truth_variable.

The file names follow the convention  truth_<source-type>_<data_type> so I suggest that <source-type> be the major ordering principle here as well.   There could be subdirectories   `truth_merged`, `truth_galaxy`, `truth_star`, and `truth_sn`. `truth_star` would contain both the summary and the variability files; similarly for `truth_sn`. truth_merged_summary would go under `truth_merged` and truth_galaxy_summary would go under `truth_galaxy`

**Comment by JoanneBogart** [comment] 2022-05-31 18:23
I don't mind the copies if we have space - just a thought.
I agree it's confusing that v2 means different things.  I was about to say that we could use, say, pv2 (where p stands for "public" or "portal"), but we already have the v2 and v4 built in other places (release note, GCRCatalogs configs) so maybe we're stuck with it.

**Comment by JoanneBogart** [comment] 2022-05-31 19:27
..so now I guess I need to fix up a bunch of GCRCatalogs configs with names like
`desc_dc2_run2.2i_truth_XXX_YYY_v1-0-0.yaml`  ?

**Comment by JoanneBogart** [comment] 2022-05-31 19:38
..and now I'm beginning to wonder if we really want a run2.2i-dr6-v4.  I'm in favor of making it explicit that the new truth datasets go with release note v4, but maybe not that way.
What about adding a subdirectory
`..run2.2i-dr6-v2/truth-pv4/..`
and then putting `truth_merged`, `truth_galaxy`, `truth_star` and `truth_sn` under that?

**Comment by heather999** [comment] 2022-05-31 23:06
I think it depends on what we really mean by `-v2` in `run2.2i-dr6-v2` for the portal.  I do recall we had this conversation and decided the v2 would be associated with the portal/release note versioning and hoped it wouldn't be confused with our internal DC2 versioning.

I don't really see a need to add `p` to the version number now, especially if we cannot apply it at the upper level of the directory structure - and I agree we really can't do that now.

The directory structure we define in gsharing is going to be replicated for the users that download this data.  So I agree having some portion of the current DC2 release under `run2.2i-dr6-v2` and other bits under `run2.2i-dr6-v4` is going to be problematic.  We want a coherent set of DC2 to reside under one top-level directory.  We can do that by either creating a full `run2.2i-dr6-v4` which means we have duplicate copies of some data OR we attempt to represent the versioning for each individual DC2 dataset.  I think I prefer the former.
Maybe I'm also hoping this is a relatively short-term problem.  Next time, after DC2 gen2, we should consider how we might version public data releases differently.

**Comment by JoanneBogart** [comment] 2022-06-01 04:15
Ok.  I don't remember the earlier conversation but don't doubt it occurred.  In that case, given where we are, this does sound like the best course for this release.   I will need to update some GCRCatalogs configs to be consistent with it.

**Comment by heather999** [comment] 2022-06-02 23:27
I've copied everything over to a new run2.2i-dr6-v4 under gsharing.  Please take a look and see if I have that right.

**Comment by JoanneBogart** [comment] 2022-06-03 21:33
I think Yao and I finally came to the conclusion that the path to truth match should be `run2.2i-dr6-v4/truth_match/truth_merged_summary_v1-0-0  based on this (resolved) discussion, but @yymao should comment

> Suggestion: change this path to /lsstdesc-public/dc2/run2.2i-dr6-v4/truth_merged as described in my comment https://github.com/LSSTDESC/desc-data-portal/issues/88
Member Author
@[yymao](https://github.com/yymao) yymao [2 days ago](https://github.com/LSSTDESC/gcr-catalogs/pull/595#discussion_r887012682)

That's fine by me. But for users, this means when they download this catalog from the portal, the directory will be named truth_merged while our release note still calls this catalog truth match?
Member
@[JoanneBogart](https://github.com/JoanneBogart) JoanneBogart [2 days ago](https://github.com/LSSTDESC/gcr-catalogs/pull/595#discussion_r887148111)

I would prefer to change the release note but don't feel strongly about it.
Member Author
@[yymao](https://github.com/yymao) yymao [2 days ago](https://github.com/LSSTDESC/gcr-catalogs/pull/595#discussion_r887225962)

I prefer not to change the release note but also don't feel strongly about it. That said, someone has to make a decision so that we can move forward. 🙂
Member
@[JoanneBogart](https://github.com/JoanneBogart) JoanneBogart [2 days ago](https://github.com/LSSTDESC/gcr-catalogs/pull/595#discussion_r887234548)

It's less work to leave it as it is, so let's leave it. No matter what we do this time around, there are going to be inconsistencies of one sort or another. It's probably better, as @heather999 suggested, to focus on doing better with organization for DP0.

**Comment by yymao** [comment] 2022-06-03 21:46
Hmm, are we trying to maintain the same structure as v2? If so, the truth_merged parquet files should be placed in `truth_match` directly, in other words, from the current structure we would need to run:
```bash
cd /global/cfs/cdirs/lsst/gsharing/lsstdesc-public/dc2/run2.2i-dr6-v4

mv truth_merged/truth_merged_summary_v1-0-0 truth_match
rmdir truth_merged
```

Unless I miss something?

**Comment by JoanneBogart** [comment] 2022-06-03 22:08
Of course we can't keep the same structure entirely since there are new catalogs. The question is whether we keep the same structure insofar as possible.   That's what I agreed to because it seemed like less work and we needed a decision.

**Comment by JoanneBogart** [comment] 2022-06-03 22:12
@heather999 everything else looks fine to me.   Sorry to have caused extra bother by resolving that conversation, which had the effect of hiding it.

**Comment by yymao** [comment] 2022-06-23 17:45
:tada:

**Closed by yymao** 2022-06-23 17:45 UTC
Labels: Type: Data Sets
